---
# delete_snapshot_vm.yml

- name: Delete the snapshots for the list of hosts
  hosts: all
  vars_files:
  - vars/vault_vmware.yml
  - vars/vmware.yml
  vars:
    current_state: remove_all

  tasks:
  - include_tasks: tasks/snapshot_action.yml
    loop: "{{ host_list }}"