---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code
  ansible.builtin.template: 
    src: "{{ item }}.j2"
    dest: "/var/www/html/{{ item }}"
  loop:
    - index.html
    - about.html
    - index.php
